/**
 * Generates a .env.example file in the parent project root (3 levels up from this file).
 * Reads only key names and descriptions from MongoDB — never real values.
 * Uses fake placeholders from utils/fakeValue.util.js.
 * Safe to commit to git.
 *
 * Combines keys from all environments into a single file with env comments.
 */
const fs = require('fs');
const path = require('path');
const Secret = require('../models/Secret.model');
const { getFakeValue } = require('../utils/fakeValue.util');
const logger = require('../config/logger');

/**
 * Generate a .env.example file in the parent project root.
 * Reads all secret keys and descriptions from MongoDB (never decrypted values),
 * and writes placeholder values using pattern-matching.
 * Shows keys from both environments.
 */
async function generateEnvExample() {
  try {
    const secrets = await Secret.find({}).sort({ key: 1 }).lean();

    if (secrets.length === 0) {
      logger.warn('generate .env.example skipped', 'no secrets in database');
      return;
    }

    // Write to the parent project root (3 levels up from this file)
    const outputPath = path.resolve(__dirname, '../../..', '.env.example');

    let content = '# .env.example\n';
    content += '# Auto-generated by secrets-manager — DO NOT commit real secrets here.\n';
    content += '# This file lists the keys your application needs.\n';
    content += '# Copy placeholder values into your actual .env file or use the secrets-manager UI/CLI.\n\n';

    let currentEnv = '';
    for (const secret of secrets) {
      if (secret.environment !== currentEnv) {
        currentEnv = secret.environment;
        content += `# ─── ${currentEnv.toUpperCase()} ──────────────────────────────────────\n\n`;
      }
      if (secret.description) {
        content += `# ${secret.description}\n`;
      }
      content += `${secret.key}=${getFakeValue(secret.key)}\n\n`;
    }

    content += '# Secrets managed via secrets-manager (local MongoDB, AES-256-GCM encrypted)\n';

    fs.writeFileSync(outputPath, content, 'utf8');
    logger.info('.env.example generated', `${outputPath} (${secrets.length} keys)`);
  } catch (err) {
    // Don't crash if this fails — it's a best-effort convenience feature
    logger.error('generate .env.example failed', err.message);
  }
}

module.exports = { generateEnvExample };